// <auto-generated />
using System;
using DVLD.INFRASTRUCTURE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVLD.INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DVLD.CORE.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("ApplicantPersonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("ApplicationStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("ApplicationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastStatusDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("smallmoney");

                    b.HasKey("ApplicationID");

                    b.HasIndex("ApplicantPersonID");

                    b.HasIndex("ApplicationTypeID");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.ApplicationType", b =>
                {
                    b.Property<int>("ApplicationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationTypeID"));

                    b.Property<decimal>("Fees")
                        .HasColumnType("smallmoney");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("ApplicationTypeID");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("ApplicationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ApplicationTypeID = 1,
                            Fees = 15m,
                            Title = "New Local Driving License Service"
                        },
                        new
                        {
                            ApplicationTypeID = 2,
                            Fees = 7m,
                            Title = "Renew Driving License Service"
                        },
                        new
                        {
                            ApplicationTypeID = 3,
                            Fees = 10m,
                            Title = "Replacement for a Lost Driving License"
                        },
                        new
                        {
                            ApplicationTypeID = 4,
                            Fees = 5m,
                            Title = "Replacement for a Damaged Driving License"
                        },
                        new
                        {
                            ApplicationTypeID = 5,
                            Fees = 15m,
                            Title = "Release Detained Driving Licsense"
                        },
                        new
                        {
                            ApplicationTypeID = 6,
                            Fees = 51m,
                            Title = "New International License"
                        },
                        new
                        {
                            ApplicationTypeID = 7,
                            Fees = 5m,
                            Title = "Retake Test"
                        });
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryID = 2,
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryID = 3,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryID = 4,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryID = 5,
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryID = 6,
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryID = 7,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryID = 8,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryID = 9,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryID = 10,
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryID = 11,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryID = 12,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryID = 13,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryID = 14,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryID = 15,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryID = 16,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryID = 17,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryID = 18,
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryID = 19,
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryID = 20,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryID = 21,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryID = 22,
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryID = 23,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryID = 24,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryID = 25,
                            CountryName = "Brunei"
                        },
                        new
                        {
                            CountryID = 26,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryID = 27,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryID = 28,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryID = 29,
                            CountryName = "Cabo Verde"
                        },
                        new
                        {
                            CountryID = 30,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryID = 31,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryID = 32,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryID = 33,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryID = 34,
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryID = 35,
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryID = 36,
                            CountryName = "China"
                        },
                        new
                        {
                            CountryID = 37,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryID = 38,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryID = 39,
                            CountryName = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            CountryID = 40,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryID = 41,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryID = 42,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryID = 43,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryID = 44,
                            CountryName = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            CountryID = 45,
                            CountryName = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            CountryID = 46,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryID = 47,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryID = 48,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryID = 49,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryID = 50,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryID = 51,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryID = 52,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryID = 53,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryID = 54,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryID = 55,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryID = 56,
                            CountryName = "Eswatini (fmr. \"Swaziland\")"
                        },
                        new
                        {
                            CountryID = 57,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryID = 58,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryID = 59,
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryID = 60,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryID = 61,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryID = 62,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            CountryID = 63,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryID = 64,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryID = 65,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryID = 66,
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryID = 67,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryID = 68,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryID = 69,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryID = 70,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryID = 71,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryID = 72,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryID = 73,
                            CountryName = "Holy See"
                        },
                        new
                        {
                            CountryID = 74,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryID = 75,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryID = 76,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryID = 77,
                            CountryName = "India"
                        },
                        new
                        {
                            CountryID = 78,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryID = 79,
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryID = 80,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryID = 81,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryID = 82,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryID = 83,
                            CountryName = "Ivory Coast"
                        },
                        new
                        {
                            CountryID = 84,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryID = 85,
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryID = 86,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryID = 87,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryID = 88,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryID = 89,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryID = 90,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryID = 91,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryID = 92,
                            CountryName = "Laos"
                        },
                        new
                        {
                            CountryID = 93,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryID = 94,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryID = 95,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryID = 96,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryID = 97,
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryID = 98,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryID = 99,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryID = 100,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryID = 101,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryID = 102,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryID = 103,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryID = 104,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryID = 105,
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryID = 106,
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryID = 107,
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            CountryID = 108,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryID = 109,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryID = 110,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryID = 111,
                            CountryName = "Micronesia"
                        },
                        new
                        {
                            CountryID = 112,
                            CountryName = "Moldova"
                        },
                        new
                        {
                            CountryID = 113,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryID = 114,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryID = 115,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryID = 116,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryID = 117,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryID = 118,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryID = 119,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryID = 120,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryID = 121,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryID = 122,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryID = 123,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryID = 124,
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryID = 125,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryID = 126,
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            CountryID = 127,
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryID = 128,
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryID = 129,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryID = 130,
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryID = 131,
                            CountryName = "Palestine State"
                        },
                        new
                        {
                            CountryID = 132,
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryID = 133,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryID = 134,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryID = 135,
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryID = 136,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryID = 137,
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryID = 138,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryID = 139,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryID = 140,
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryID = 141,
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryID = 142,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryID = 143,
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryID = 144,
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryID = 145,
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryID = 146,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryID = 147,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryID = 148,
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryID = 149,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryID = 150,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryID = 151,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryID = 152,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryID = 153,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryID = 154,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryID = 155,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryID = 156,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryID = 157,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryID = 158,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryID = 159,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryID = 160,
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            CountryID = 161,
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryID = 162,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryID = 163,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryID = 164,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            CountryID = 165,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryID = 166,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryID = 167,
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryID = 168,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryID = 169,
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            CountryID = 170,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryID = 171,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            CountryID = 172,
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryID = 173,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryID = 174,
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryID = 175,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryID = 176,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryID = 177,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryID = 178,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryID = 179,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryID = 180,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryID = 181,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryID = 182,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryID = 183,
                            CountryName = "United States of America"
                        },
                        new
                        {
                            CountryID = 184,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryID = 185,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryID = 186,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryID = 187,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            CountryID = 188,
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            CountryID = 189,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryID = 190,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryID = 191,
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("DVLD.CORE.Entities.DetainedLicense", b =>
                {
                    b.Property<int>("DetainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetainID"));

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetainDate")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal>("FineFees")
                        .HasColumnType("smallmoney");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<int>("LicenseID")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("ReleasedByUserID")
                        .HasColumnType("int");

                    b.HasKey("DetainID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("LicenseID");

                    b.HasIndex("ReleaseApplicationID");

                    b.HasIndex("ReleasedByUserID");

                    b.ToTable("DetainedLicenses", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);

                    b.HasData(
                        new
                        {
                            DriverID = 1,
                            CreatedByUserID = 2,
                            CreatedDate = new DateTime(2026, 2, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PersonID = 1
                        },
                        new
                        {
                            DriverID = 2,
                            CreatedByUserID = 3,
                            CreatedDate = new DateTime(2026, 2, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PersonID = 2
                        });
                });

            modelBuilder.Entity("DVLD.CORE.Entities.InternationalLicense", b =>
                {
                    b.Property<int>("InternationalLicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternationalLicenseID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("IssuedUsingLocalLicenseID")
                        .HasColumnType("int");

                    b.HasKey("InternationalLicenseID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("DriverID");

                    b.HasIndex("IssuedUsingLocalLicenseID");

                    b.ToTable("InternationalLicenses", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.License", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("IssueReason")
                        .HasColumnType("tinyint");

                    b.Property<int>("LicenseClassID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("smallmoney");

                    b.HasKey("LicenseID");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("DriverID");

                    b.HasIndex("LicenseClassID");

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.LicenseClass", b =>
                {
                    b.Property<int>("LicenseClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseClassID"));

                    b.Property<string>("ClassDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("ClassFees")
                        .HasColumnType("smallmoney");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<byte>("DefaultValidityLength")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MinimumAllowedAge")
                        .HasColumnType("tinyint");

                    b.HasKey("LicenseClassID");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("LicenseClasses", (string)null);

                    b.HasData(
                        new
                        {
                            LicenseClassID = 1,
                            ClassDescription = "Small motorcycles with engine capacity less than 125cc.",
                            ClassFees = 15m,
                            ClassName = "Class 1 - Small Motorcycle",
                            DefaultValidityLength = (byte)5,
                            MinimumAllowedAge = (byte)16
                        },
                        new
                        {
                            LicenseClassID = 2,
                            ClassDescription = "Motorcycles with engine capacity more than 125cc.",
                            ClassFees = 30m,
                            ClassName = "Class 2 - Heavy Motorcycle",
                            DefaultValidityLength = (byte)5,
                            MinimumAllowedAge = (byte)18
                        },
                        new
                        {
                            LicenseClassID = 3,
                            ClassDescription = "Standard cars and small pickups. (Most Common)",
                            ClassFees = 20m,
                            ClassName = "Class 3 - Ordinary driving license",
                            DefaultValidityLength = (byte)10,
                            MinimumAllowedAge = (byte)18
                        },
                        new
                        {
                            LicenseClassID = 4,
                            ClassDescription = "Vehicles used for commercial purposes like Taxis and small buses.",
                            ClassFees = 200m,
                            ClassName = "Class 4 - Commercial",
                            DefaultValidityLength = (byte)10,
                            MinimumAllowedAge = (byte)21
                        },
                        new
                        {
                            LicenseClassID = 5,
                            ClassDescription = "Agricultural tractors and specialized machinery.",
                            ClassFees = 50m,
                            ClassName = "Class 5 - Agricultural",
                            DefaultValidityLength = (byte)10,
                            MinimumAllowedAge = (byte)18
                        },
                        new
                        {
                            LicenseClassID = 6,
                            ClassDescription = "Trucks with total weight between 3.5 and 7.5 tons.",
                            ClassFees = 250m,
                            ClassName = "Class 6 - Small and Medium Truck",
                            DefaultValidityLength = (byte)10,
                            MinimumAllowedAge = (byte)21
                        },
                        new
                        {
                            LicenseClassID = 7,
                            ClassDescription = "Large trucks and trailers with weight exceeding 7.5 tons.",
                            ClassFees = 300m,
                            ClassName = "Class 7 - Heavy Truck",
                            DefaultValidityLength = (byte)10,
                            MinimumAllowedAge = (byte)21
                        });
                });

            modelBuilder.Entity("DVLD.CORE.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.Property<int>("LocalDrivingLicenseApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalDrivingLicenseApplicationID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("LicenseClassID")
                        .HasColumnType("int");

                    b.HasKey("LocalDrivingLicenseApplicationID");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("LicenseClassID");

                    b.ToTable("LocalDrivingLicenseApplications", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<byte>("Gendor")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("NationalNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<int>("NationalityCountryID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("PersonID");

                    b.HasIndex("NationalNo")
                        .IsUnique();

                    b.HasIndex("NationalityCountryID");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(2005, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jone@example.com",
                            FirstName = "jone",
                            Gendor = (byte)0,
                            LastName = "",
                            NationalNo = "N2746744",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "max",
                            ThirdName = "alax"
                        },
                        new
                        {
                            PersonID = 2,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(1998, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ben@example.com",
                            FirstName = "ben",
                            Gendor = (byte)0,
                            ImagePath = "e0acd4bc-4e9a-4ef2-b345-fb90bd39ba84.avif",
                            LastName = "",
                            NationalNo = "N253234",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "park",
                            ThirdName = "jake"
                        },
                        new
                        {
                            PersonID = 3,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(2005, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Better@example.com",
                            FirstName = "Better",
                            Gendor = (byte)0,
                            ImagePath = "ddeb3e90-c473-41ad-bdaf-519fb194cb98.avif",
                            LastName = "",
                            NationalNo = "N2742234",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "Make",
                            ThirdName = "Maksuel"
                        },
                        new
                        {
                            PersonID = 4,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(1998, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alxander@example.com",
                            FirstName = "Alxander",
                            Gendor = (byte)0,
                            ImagePath = "425d43ef-7226-459a-8556-0e71bbf9633d.avif",
                            LastName = "met",
                            NationalNo = "N1224437",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "Karter",
                            ThirdName = "max"
                        },
                        new
                        {
                            PersonID = 5,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(1998, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jonson@example.com",
                            FirstName = "jonson",
                            Gendor = (byte)0,
                            ImagePath = "c76dd4de-31c9-4b22-b7d5-521212046c51.avif",
                            LastName = "ben",
                            NationalNo = "N1224227",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "wllet",
                            ThirdName = "marker"
                        },
                        new
                        {
                            PersonID = 6,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(2005, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adim@example.com",
                            FirstName = "Adim",
                            Gendor = (byte)0,
                            LastName = "",
                            NationalNo = "N2586744",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "Elson",
                            ThirdName = "max"
                        },
                        new
                        {
                            PersonID = 7,
                            Address = "123 Amman St, Al-Abdali District",
                            DateOfBirth = new DateTime(2005, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rafile@example.com",
                            FirstName = "Rafile",
                            Gendor = (byte)0,
                            LastName = "",
                            NationalNo = "N274264",
                            NationalityCountryID = 80,
                            Phone = "0791234567",
                            SecondName = "gurge",
                            ThirdName = "carter"
                        });
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestID"));

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TestAppointmentID")
                        .HasColumnType("int");

                    b.Property<bool>("TestResult")
                        .HasColumnType("bit");

                    b.HasKey("TestID");

                    b.HasIndex("TestAppointmentID")
                        .IsUnique();

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.TestAppointment", b =>
                {
                    b.Property<int>("TestAppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestAppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LocalDrivingLicenseApplicationID")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("smallmoney");

                    b.Property<int?>("RetakeTestApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeID")
                        .HasColumnType("int");

                    b.HasKey("TestAppointmentID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("LocalDrivingLicenseApplicationID");

                    b.HasIndex("RetakeTestApplicationID");

                    b.ToTable("TestAppointments", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.TestType", b =>
                {
                    b.Property<int>("TestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("Fees")
                        .HasColumnType("smallmoney");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("TestTypeID");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("TestTypes", (string)null);

                    b.HasData(
                        new
                        {
                            TestTypeID = 1,
                            Description = "Eye vision examination",
                            Fees = 10m,
                            Title = "Vision Test"
                        },
                        new
                        {
                            TestTypeID = 2,
                            Description = "Theoretical driving rules test",
                            Fees = 20m,
                            Title = "Written Test"
                        },
                        new
                        {
                            TestTypeID = 3,
                            Description = "Practical driving test on the road",
                            Fees = 30m,
                            Title = "Street Test"
                        });
                });

            modelBuilder.Entity("DVLD.CORE.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("UserID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Application", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Person", "PersonInfo")
                        .WithMany()
                        .HasForeignKey("ApplicantPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.ApplicationType", "ApplicationTypeInfo")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.User", "CreatedByUserInfo")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationTypeInfo");

                    b.Navigation("CreatedByUserInfo");

                    b.Navigation("PersonInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.DetainedLicense", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.User", "CreatedByUserInfo")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.License", "LicenseInfo")
                        .WithMany("DetainedRecords")
                        .HasForeignKey("LicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.Application", null)
                        .WithMany()
                        .HasForeignKey("ReleaseApplicationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD.CORE.Entities.User", "ReleasedByUserInfo")
                        .WithMany()
                        .HasForeignKey("ReleasedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUserInfo");

                    b.Navigation("LicenseInfo");

                    b.Navigation("ReleasedByUserInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Driver", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Person", "PersonInfo")
                        .WithOne()
                        .HasForeignKey("DVLD.CORE.Entities.Driver", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.InternationalLicense", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Application", "ApplicationInfo")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.User", "CreatedByUserInfo")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.Driver", "DriverInfo")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.License", "LocalLicenseInfo")
                        .WithMany()
                        .HasForeignKey("IssuedUsingLocalLicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationInfo");

                    b.Navigation("CreatedByUserInfo");

                    b.Navigation("DriverInfo");

                    b.Navigation("LocalLicenseInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.License", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Application", "ApplicationInfo")
                        .WithOne()
                        .HasForeignKey("DVLD.CORE.Entities.License", "ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.Driver", "DriverInfo")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.LicenseClass", "LicenseClassInfo")
                        .WithMany()
                        .HasForeignKey("LicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationInfo");

                    b.Navigation("DriverInfo");

                    b.Navigation("LicenseClassInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Application", "ApplicationInfo")
                        .WithOne()
                        .HasForeignKey("DVLD.CORE.Entities.LocalDrivingLicenseApplication", "ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.LicenseClass", "LicenseClassInfo")
                        .WithMany()
                        .HasForeignKey("LicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationInfo");

                    b.Navigation("LicenseClassInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Person", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Country", "CountryInfo")
                        .WithMany()
                        .HasForeignKey("NationalityCountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountryInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.Test", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.TestAppointment", "TestAppointmentInfo")
                        .WithOne("TestRecord")
                        .HasForeignKey("DVLD.CORE.Entities.Test", "TestAppointmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestAppointmentInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.TestAppointment", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.LocalDrivingLicenseApplication", "LocalAppInfo")
                        .WithMany()
                        .HasForeignKey("LocalDrivingLicenseApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DVLD.CORE.Entities.Application", "RetakeTestAppInfo")
                        .WithMany()
                        .HasForeignKey("RetakeTestApplicationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocalAppInfo");

                    b.Navigation("RetakeTestAppInfo");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.User", b =>
                {
                    b.HasOne("DVLD.CORE.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("DVLD.CORE.Entities.User", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.License", b =>
                {
                    b.Navigation("DetainedRecords");
                });

            modelBuilder.Entity("DVLD.CORE.Entities.TestAppointment", b =>
                {
                    b.Navigation("TestRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
